// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD91uuHDDMlaX8r2MN9cCKmedcOTqO8D8E',
    appId: '1:1017215910567:web:c403fc8aaf4b70624b9182',
    messagingSenderId: '1017215910567',
    projectId: 'qlct2026',
    authDomain: 'qlct2026.firebaseapp.com',
    storageBucket: 'qlct2026.firebasestorage.app',
    measurementId: 'G-EMJXP6NX8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiA5Y0SUN7f8yWfwm-TOZ_7UjwdYLcp9g',
    appId: '1:1017215910567:android:643dfae25bb079ca4b9182',
    messagingSenderId: '1017215910567',
    projectId: 'qlct2026',
    storageBucket: 'qlct2026.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD91uuHDDMlaX8r2MN9cCKmedcOTqO8D8E',
    appId: '1:1017215910567:web:e83609f2120743984b9182',
    messagingSenderId: '1017215910567',
    projectId: 'qlct2026',
    authDomain: 'qlct2026.firebaseapp.com',
    storageBucket: 'qlct2026.firebasestorage.app',
    measurementId: 'G-78B8QL9TTW',
  );
}
